version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog159
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: